export const T = {
  bg: '#F4F4F6',
  card: '#FFFFFF',
  s1: '#F0F0F4',
  s2: '#E8E8EE',
  s3: '#DCDCE8',
  line: '#EBEBF0',
  lineB: '#DCDCE6',
  t1: '#0D0D18',
  t2: '#38384E',
  t3: '#86869A',
  t4: '#B4B4C8',
  gold: '#C4A44A',
  goldD: '#97791E',
  goldL: '#FAF4E4',
  goldM: '#E8D48A',
  go: '#0A7855',   goL: '#E6F5EF',  goM: '#9ADBC4',
  flag: '#BF3728', flagL: '#FDF0EE', flagM: '#EDADA6',
  warn: '#B05208', warnL: '#FEF4EE', warnM: '#F5C49A',
  info: '#1756A8', infoL: '#EDF3FC', infoM: '#ACCAEE',
  vio: '#5B30AC',  vioL: '#F2EEF9', vioM: '#C4B4E8',
  teal: '#0C6E8C', tealL: '#EDF8FB', tealM: '#9ED4E4',
} as const;

export const STATUS: Record<string, { label: string; color: string; bg: string; border: string }> = {
  available:     { label: 'Available',     color: T.go,    bg: T.goL,   border: T.goM },
  reserved:      { label: 'Reserved',      color: T.info,  bg: T.infoL, border: T.infoM },
  sale_agreed:   { label: 'Sale Agreed',   color: T.goldD, bg: T.goldL, border: T.goldM },
  exchanged:     { label: 'Exchanged',     color: T.vio,   bg: T.vioL,  border: T.vioM },
  contracts_out: { label: 'Contracts Out', color: T.goldD, bg: T.goldL, border: T.goldM },
  let_agreed:    { label: 'Let Agreed',    color: T.teal,  bg: T.tealL, border: T.tealM },
  enquiry:       { label: 'Enquiry',       color: T.t3,    bg: T.s1,    border: T.line },
  new_lead:      { label: 'New Lead',      color: T.warn,  bg: T.warnL, border: T.warnM },
  pending:       { label: 'Pending',       color: T.warn,  bg: T.warnL, border: T.warnM },
  confirmed:     { label: 'Confirmed',     color: T.go,    bg: T.goL,   border: T.goM },
} as const;
